name = "hono-urlshortener"
compatibility_date = "2023-12-01"

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "HONOLINK"
id = "328ed2a80a724f998592ef82d7c72a01"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
